### PR TITLE
Chore: Drupal 10 compatibility

### PR DESCRIPTION
**Pull request by Adnan-cds**
Declaring Drupal 10 compatibility of this module.

### CODE REVIEW

**Comment by finnlewis** [comment]
@Adnan-cds some coding standards and a test failing. Coding standards look quick, but not sure about the test.

**Comment by Adnan-cds** [comment]
> but not sure about the test.

Ah.. fixed now.  The Github actions file was outdated and was testing the entire localgov test suite instead of just this module.

**Review by finnlewis — APPROVED** [review]
Looks good to me and the tests pass :smile: thanks @Adnan-cds !

**Comment by Adnan-cds** [comment]
Thanks.  Merging...

**Pull request merged**
